apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: screamingfrog-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: "nginx"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: screamingfrog-service
            port:
              number: 443
  tls:
  - secretName: screamingfrog-tls-secret

