apiVersion: v1
kind: Service
metadata:
  name: screamingfrog-service
spec:
  selector:
    app: screamingfrog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
